### ISSUE TITLE
Is sdoc-merge broken in v2?

### ISSUE THREAD

**Issue by mikdiet** [zzak/sdoc#152]
I'm trying to generate merged documentation for rails+ruby. 

Separate docs were generated well, and looks well too.

When I run 
```bash
bundle exec sdoc-merge --title "Rails v6.0.3.5, Ruby v2.6.6" --op public --names "rails, ruby" railsdoc rubydoc
``` 
I don't get any error, but result is not well. It seems like it tries to generate in sdoc v1 style (with frames)

<img width="1085" alt="Screenshot 2021-02-27 at 12 23 26" src="https://user-images.githubusercontent.com/426230/109383300-bf32d680-78f6-11eb-9ff4-24b320286095.png">
<img width="229" alt="Screenshot 2021-02-27 at 12 24 01" src="https://user-images.githubusercontent.com/426230/109383303-c3f78a80-78f6-11eb-9a55-1d11d86baa77.png">

**Comment by zzak** [comment]
Hi @mikdiet,

`sdoc-merge` isn't something we've really been actively working on, the recent version upgrades have mainly focused on redesigning the HTML&CSS. I'm not even sure who uses it, and there definitely aren't any tests afaict.

That said, [the code](https://github.com/zzak/sdoc/blob/master/lib/sdoc/merge.rb) looks fairly straight-forward. Since you're using it, if you'd be interested in helping maintain it I'd be happy to add you as a committer :)

Thanks!
